"""Added trip description

Revision ID: 7681d0d038c2
Revises: 58da345e5f68
Create Date: 2023-12-23 22:24:05.212796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7681d0d038c2"
down_revision = "58da345e5f68"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips",
        sa.Column(
            "description",
            sa.String(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "description")
    # ### end Alembic commands ###
