"""empty message

Revision ID: d774b20ea55c
Revises: 59d46ba00537
Create Date: 2023-12-22 15:53:57.900832

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d774b20ea55c"
down_revision = "59d46ba00537"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###
