"""Fixed category field to integer

Revision ID: 24663b098d44
Revises: 7681d0d038c2
Create Date: 2023-12-23 23:53:45.246654

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24663b098d44"
down_revision = "7681d0d038c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "markers",
        "category",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "markers",
        "category",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
