"""empty message

Revision ID: 59d46ba00537
Revises: 0a22b8f84960
Create Date: 2023-12-22 04:44:55.467078

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59d46ba00537"
down_revision = "0a22b8f84960"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("profile_picture", sa.String(), nullable=True))
    op.drop_column("users", "fullname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("fullname", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "profile_picture")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
