"""Added audit log schema

Revision ID: 3c5727a374c3
Revises: 03533ceead47
Create Date: 2024-01-12 19:54:09.646242

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils import ChoiceType

from MapsPlanner_API.db.models.AuditLog import EAuditLog

# revision identifiers, used by Alembic.
revision = "3c5727a374c3"
down_revision = "03533ceead47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", ChoiceType(EAuditLog, impl=sa.Integer()), nullable=False),
        sa.Column("extra", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit")
    # ### end Alembic commands ###
