version: '3.9'


services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: maps_planner_api:${MAPSPLANNER_API_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.8-bullseye
    hostname: maps_planner_api-db
    env_file: .env
    volumes:
      - maps_planner_api-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U maps_planner_api
      interval: 2s
      timeout: 3s
      retries: 40
  migrator:
    image: maps_planner_api:${MAPSPLANNER_API_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  maps_planner_api-db-data:
    name: maps_planner_api-db-data
