version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8888:8888"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      reload: "True"
  db:
    ports:
      - "15432:5432"

