name: Testing MapsPlanner_API

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:

      MapsPlanner_API-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: MapsPlanner_API
          POSTGRES_USER: MapsPlanner_API
          POSTGRES_DB: MapsPlanner_API
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="MapsPlanner_API" .
      env:
        host: 0.0.0.0
        port: 8888
        db_host: localhost
        db_port: 15432
        db_user: maps_planner_api
        db_pass: maps_planner_api
        db_base: maps_planner_api_pytest
        environment: pytest
        backend_url: http://localhost:8888
        frontend_url: http://localhost:5173

        google_auth_client_id: ""
        google_auth_client_secret: ""
        maptiler_api_key: ""
        chatgpt_api_key: ""

        user_auto_approval: false
        log_level: DEBUG
